# https://docs.aws.amazon.com/ko_kr/codedeploy/latest/userguide/reference-appspec-file-example.html#appspec-file-example-server
version: 0.0
os: linux
files:
  - source: arirang-first/
    destination: /home/ubuntu/arirang-first/build/

permissions:
  - object: arirang-first/
    pattern : "**"
    mode : 755
    owner : ubuntu
    group : ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: healthCheck.sh
      timeout: 60
      runas: ubuntu
